version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - kc_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 3s
      timeout: 3s
      retries: 20
    networks:
      - kcnet


  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    restart: unless-stopped

    command:
      - start-dev
      - --optimized
      - --db=postgres
      - --db-url=jdbc:postgresql://postgres:5432/keycloak
      - --db-username=keycloak
      - --db-password=keycloak
      - --hostname-strict=false

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres

    ports:
      - "8080:8080"

    networks:
      - kcnet


  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    restart: unless-stopped
    networks:
      - kcnet


  kong:
    image: kong/kong-gateway:3.9.0.0
    container_name: kong
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /opt/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug
    volumes:
      - ./kong/kong.yml:/opt/kong/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - keycloak
      - httpbin
    networks:
      - kcnet


volumes:
  kc_db:

networks:
  kcnet:
    driver: bridge