version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - kc_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 3s
      timeout: 3s
      retries: 20
    networks:
      - kcnet

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    restart: unless-stopped

    command:
      - start-dev
      - --db=postgres
      - --db-url-host=postgres
      - --db-url-database=keycloak
      - --db-username=keycloak
      - --db-password=keycloak
      - --hostname-strict=false

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - "8080:8080"

    volumes:
      - ./realm:/opt/keycloak/data/import

    networks:
      - kcnet

  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    networks:
      - kcnet

  kong:
    build:
      context: ./kong
      dockerfile: Dockerfile
    container_name: kong
    env_file:
      - ./kong/.env
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /opt/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      keycloak:
        condition: service_started
      httpbin:
        condition: service_started
    volumes:
      - ./kong/kong.yml:/opt/kong/kong.yml:ro
    ports:
      - "8000:8000"   # proxy
      - "8001:8001"   # admin
    networks:
      - kcnet

volumes:
  kc_db:

networks:
  kcnet:
    driver: bridge